# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://rahulgarg12.github.io/
baseurl: 
title: Rahul Garg
author: Rahul Garg
description: Personal blog and resume
avatar: profile.png
email: rahul_garg@outlook.com
github: rahulgarg12 # username
linkedin: rahulgarg12
facebook: rahulgarg.delhi
twitter: RhlGarg
skype: rahulgarg.delhi
mobile: +91 9717384893

# needed for travis-ci build
exclude: [vendor]
